### ISSUE TITLE
Can not read txt file: UnicodeDecodeError

### ISSUE THREAD

**Issue by yomajo** [maroofi/csvtool#1]
```
Traceback (most recent call last):
  File "/home/anon/.local/bin/csvtool", line 8, in <module>
    sys.exit(main())
  File "/home/anon/.local/lib/python3.10/site-packages/csvtool/csvtool.py", line 141, in main
    header = reader.__next__()
  File "/usr/lib/python3.10/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1976: ordinal not in range(128)
```

Read with dd:
```
>>dd if=test.txt bs=1 count=5 skip=1975 status=none
>>péro
```

**Comment by maroofi** [comment]
Hi yomajo,
Are you using the latest code on github? because it's not updated on PyPi.
Please install it from git directly.
If you still have error, it would be nice to upload a sample .csv file for this case.
Thanks,

**Comment by yomajo** [comment]
```
>>csvtool --version
>>CSVTOOL version 0.3. Use --help to see logn description.
```

I installed it the recommended way like a month ago (almost certain, you can verify the versioning), and yesterday tried it for first time.

Unfortunately, can't provide the .txt file since it contains people's addresses. I have extracted the trouble causing string/character. See bottom of original post.

**Comment by maroofi** [comment]
Thanks for the feedback.
Clearly the problem is encoding. I added **--encoding** switch to specify the encoding of the file if you know it.
This can solve the problem.
for example you can specify **--encoding 'utf-8'**
Thanks again.

**Comment by yomajo** [comment]
Yes, that solves it. Although chardet incorrectly guesses my file and fails to open without provided `utf-8`
